//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class MarkersTypeMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/MarkersType";
        public override string RosMessageName => k_RosMessageName;

        public int c;
        public int s;
        public int m;

        public MarkersTypeMsg()
        {
            this.c = 0;
            this.s = 0;
            this.m = 0;
        }

        public MarkersTypeMsg(int c, int s, int m)
        {
            this.c = c;
            this.s = s;
            this.m = m;
        }

        public static MarkersTypeMsg Deserialize(MessageDeserializer deserializer) => new MarkersTypeMsg(deserializer);

        private MarkersTypeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.c);
            deserializer.Read(out this.s);
            deserializer.Read(out this.m);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.c);
            serializer.Write(this.s);
            serializer.Write(this.m);
        }

        public override string ToString()
        {
            return "MarkersTypeMsg: " +
            "\nc: " + c.ToString() +
            "\ns: " + s.ToString() +
            "\nm: " + m.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
